### ISSUE TITLE
Filtering posts by open ping_status returns posts with closed ping_status

### ISSUE THREAD

**Issue by jamieburchell** [wp-cli/entity-command#453] opened 2024-01-08 11:06 UTC
## Bug Report

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [X] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

`wp post --ping_status=open` returns posts with a `ping_status` of closed. The posts returned are sticky posts.

**Describe how other contributors can replicate this bug**

```
wp post list --ping_status=open --fields=ID,post_status,post_type,ping_status
+------+-------------+-----------+-------------+
| ID   | post_status | post_type | ping_status |
+------+-------------+-----------+-------------+
| 2521 | publish     | post      | closed      |
| 2508 | publish     | post      | closed      |
+------+-------------+-----------+-------------+

wp post list --ping_status=open --format=ids
(no output)

wp post list --ping_status=foobar --fields=ID,post_status,post_type,ping_status
+------+-------------+-----------+-------------+
| ID   | post_status | post_type | ping_status |
+------+-------------+-----------+-------------+
| 2521 | publish     | post      | closed      |
| 2508 | publish     | post      | closed      |
+------+-------------+-----------+-------------+
```

**Describe what you would expect as the correct outcome**

Command should return no results as there are no posts with `ping_status` of `open`

**Let us know what environment you are running this on**

```
OS:     Linux 4.18.0-513.9.1.el8_9.x86_64 #1 SMP Wed Nov 29 18:55:19 UTC 2023 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php
PHP version:    8.1.27
php.ini used:   /etc/php.ini
MySQL binary:   /bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.5.22-MariaDB, for Linux (x86_64) using  EditLine wrapper
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www
WP-CLI packages dir:
WP-CLI cache dir:       /home/deploy/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:  /var/www/wp-cli.yml
WP-CLI version: 2.9.0
```

**Comment by shawnhooper** [comment] 2024-01-16 04:22
Attempted to reproduce this issue on my local, without success.

Listing posts with the `--ping_status=open` / `--ping_status=closed` flag displayed the expected results.

**Comment by jamieburchell** [comment] 2024-01-16 07:54
@shawnhooper I can still repro as above. Those two posts are output even if `post_status` is `foobar`.

I'll copy the site locally and prod around to see if I can find what's going on.

**Comment by jamieburchell** [comment] 2024-01-16 08:58
@shawnhooper The two posts in question are sticky posts.

**Comment by shawnhooper** [comment] 2024-01-16 19:16
@jamieburchell Ah, yep, that does it. 

This functions the same way as the WP_Query loop.  I'll ask for a second opinion, but I don't think we should change this, since: 

1. This functions the same way as the WP_Query loop. 
2. This would be a breaking change

I did, however, figure out that you can ignore the sticky flag by adding `--ignore_sticky_posts=1` to the WP-CLI command:

`wp post list --ping_status=open --fields=ID,post_status,post_type,ping_status --ignore_sticky_posts=1`

**Comment by jamieburchell** [comment] 2024-01-16 19:34
@shawnhooper I understand. But it's not even consistent. If you just change the format attribute to return IDs, the sticky posts aren't output.

**Comment by shawnhooper** [comment] 2024-01-16 20:12
@jamieburchell Aah, right you are.  Ok, I'll look into that a bit deeper then.  Thanks.

**Comment by danielbachhuber** [comment] 2024-01-30 21:27
@jamieburchell @shawnhooper I created three posts:

```
$ wp post list --fields=ID,post_title,post_status,ping_status
+----+--------------------+-------------+-------------+
| ID | post_title         | post_status | ping_status |
+----+--------------------+-------------+-------------+
| 6  | Ping closed sticky | draft       | closed      |
| 4  | Ping closed        | draft       | closed      |
| 1  | Ping open          | draft       | open        |
+----+--------------------+-------------+-------------+
```

Filtering to `ping_status=closed` works as expected:

```
$ wp post list --fields=ID,post_title,post_status,ping_status --ping_status=closed
+----+--------------------+-------------+-------------+
| ID | post_title         | post_status | ping_status |
+----+--------------------+-------------+-------------+
| 6  | Ping closed sticky | draft       | closed      |
| 4  | Ping closed        | draft       | closed      |
+----+--------------------+-------------+-------------+
$ wp post list --fields=ID,post_title,post_status,ping_status --ping_status=closed --format=ids
6 4
```

Filtering to `ping_status=open` works as expected:

```
$ wp post list --fields=ID,post_title,post_status,ping_status --ping_status=open
+----+------------+-------------+-------------+
| ID | post_title | post_status | ping_status |
+----+------------+-------------+-------------+
| 1  | Ping open  | draft       | open        |
+----+------------+-------------+-------------+
$ wp post list --fields=ID,post_title,post_status,ping_status --ping_status=open --format=ids
1
```

Is there something I'm missing? Maybe the problem in your environments is caused by custom code?

**Comment by jamieburchell** [comment] 2024-01-30 22:34
@danielbachhuber Maybe try it with published posts. I can still repro original findings with active no plugins or custom code.

Wondering if [this](https://github.com/wp-cli/entity-command/issues/278) is relevant.

**Comment by danielbachhuber** [comment] 2024-01-31 00:16
> Maybe try it with published posts.

@jamieburchell Ah, that was it:

```
$ wp post list --fields=ID,post_title,post_status,ping_status
+----+--------------------+-------------+-------------+
| ID | post_title         | post_status | ping_status |
+----+--------------------+-------------+-------------+
| 6  | Ping closed sticky | publish     | closed      |
| 1  | Ping open          | publish     | open        |
| 4  | Ping closed        | publish     | closed      |
+----+--------------------+-------------+-------------+
$ wp post list --fields=ID,post_title,post_status,ping_status --ping_status=closed
+----+--------------------+-------------+-------------+
| ID | post_title         | post_status | ping_status |
+----+--------------------+-------------+-------------+
| 6  | Ping closed sticky | publish     | closed      |
| 4  | Ping closed        | publish     | closed      |
+----+--------------------+-------------+-------------+
$ wp post list --fields=ID,post_title,post_status,ping_status --ping_status=closed --format=ids
4 6
$ wp post list --fields=ID,post_title,post_status,ping_status --ping_status=open
+----+--------------------+-------------+-------------+
| ID | post_title         | post_status | ping_status |
+----+--------------------+-------------+-------------+
| 6  | Ping closed sticky | publish     | closed      |
| 1  | Ping open          | publish     | open        |
+----+--------------------+-------------+-------------+
$ wp post list --fields=ID,post_title,post_status,ping_status --ping_status=open --format=ids
1
```

Here's the only thing we do differently:

https://github.com/wp-cli/entity-command/blob/26fadf26b9083e078d00375764dbe84bbf07c7a0/src/Post_Command.php#L645-L646

I don't [see an explicit report for it in Trac](https://core.trac.wordpress.org/search?q=sticky+ids&noquickjump=1&changeset=on&ticket=on). Want to create a ticket there for it?

**Comment by jamieburchell** [comment] 2024-01-31 08:17
> I don't [see an explicit report for it in Trac](https://core.trac.wordpress.org/search?q=sticky+ids&noquickjump=1&changeset=on&ticket=on). Want to create a ticket there for it?

[Done](https://core.trac.wordpress.org/ticket/60395#no3)

**Comment by danielbachhuber** [comment] 2024-01-31 10:51
Thanks! Replied on that with some clarification.

Closing this issue because it's an upstream bug.

**Closed by danielbachhuber** 2024-01-31 10:51 UTC
Labels: state:unconfirmed
