### ISSUE TITLE
WP network meta  not working

### ISSUE THREAD

**Issue by HW-Siew** [wp-cli/entity-command#130] opened 2018-01-16 02:48 UTC
Hi, I have a multisite configuration setup and multiple subsites created. I am trying to update one of the subsite's url (says id=3) using wp network meta. However, i noticed it didn't get updated.

I tried to list all value using wp network list <id>. It seems to be the command is working only on primary site (id=1) but not others. All other subsites other than primary site (id=1) returned empty table as shown below.

+---------+----------+------------+
|   site_id    | meta_key | meta_value |
+---------+----------+------------+
+---------+----------+------------+

What could be the possible reason for this? 

Thanks for the advice in advance.

**Comment by schlessera** [comment] 2018-01-16 07:36
Hello @HW-Siew ,

I just tested this, and it Works as expected in my tests. I'm closing this as it seems to be an issue with your installation.
 
GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support

**Closed by schlessera** 2018-01-16 07:36 UTC
Labels: state:unsupported
